spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/demo_feign_data   # changed from mysql → localhost
    username: root
    password: Banti@321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-container:8761/eureka   # changed from eurekaservice
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
