spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/demo_feign_data
    username: root
    password: Banti@321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: env,health,info

  tracing:
    trace-id128: false
    sampling:
      probability: 1.0   # dev only (reduce in prod)
    export:
      enabled: true     # ✅ REQUIRED for Boot 4

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
